apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingress-entries.daniel.iti.com
spec:
  group: daniel.iti.com
  scope: Namespaced
  names:
    plural: ingress-entries
    singular: ingress-entry
    kind: IngressEntry
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              service:
                type: string
              path:
                type: string
              port:
                type: number
    additionalPrinterColumns:
    - jsonPath: .spec.service
      name: Service
      type: string
    - jsonPath: .spec.path
      name: Path
      type: string
    - jsonPath: .spec.port
      name: Port
      type: number
