apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-entries-daniel-iti-com-type-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-entries-daniel-iti-com-type-pods
  template:
    metadata:
      labels:
        app: ingress-entries-daniel-iti-com-type-pods
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config